config/routes.rb
Rails.application.routes.draw do
  resources :actors do
		get :autocomplete_actor_name, on: :collection
	end

  devise_for :users
  resources :films
  resources :users
	root 'films#index'

	get '/list_films', to: 'films#list_films'
	get '/list_actors', to: 'actors#index'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
	validates_presence_of :born_year, :name, :born_place, :bio
	has_and_belongs_to_many :films

	def to_s
		name
	end

	def years_from_now
		Time.now.year - born_year.year
	end
end

app/models/film.rb
class Film < ActiveRecord::Base
	validates :year, numericality: { only_integer: true }
	before_save :strip_whitespaces
	has_and_belongs_to_many :actors

	private
	def strip_whitespaces
		self.title.strip!
		self.image.strip!
		self.director.strip!
		self.description.strip!
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]
	respond_to :html
	autocomplete :actor, :name, full: true

  def index
    @actors = Actor.all
    respond_with(@actors)
  end

  def show
    respond_with(@actor)
  end

  def new
    @actor = Actor.new
    respond_with(@actor)
  end

  def edit
  end

  def create
    @actor = Actor.new(actor_params)
    @actor.save
    respond_with(@actor)
  end

  def update
    @actor.update(actor_params)
    respond_with(@actor)
  end

  def destroy
    @actor.destroy
    respond_with(@actor)
  end

  private
    def set_actor
      @actor = Actor.find(params[:id])
    end

    def actor_params
      params.require(:actor).permit(:name, :born_year, :born_place, :bio)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]
	before_action :set_carousel, only: :index
	respond_to :html

  def index
    @films = Film.all
    respond_with(@films)
  end

  def show
    respond_with(@film)
  end

  def new
    @film = Film.new
    respond_with(@film)
  end

  def edit
  end

  def create
    @film = Film.new(film_params)
		@actors = params[:actors].strip.split(',')
		@actors.each{|a| @film.actors << Actor.find_by_name(a.strip)}
    @film.save
    respond_with(@film)
  end

  def update
		@film.actors.clear
		@actors = params[:actors].strip.split(',')
		@actors.each{|a| @film.actors << Actor.find_by_name(a.strip)}
	  flash[:notice] = "Film was successfully updated." if @film.update(film_params)
    respond_with(@film, :location => list_films_path)
  end

  def destroy
    @film.destroy
    respond_with(@film)
  end


	def list_films
		@films = Film.all
		respond_with(@films)
	end


  private
    def set_film
      @film = Film.find(params[:id])
    end

		def set_carousel
			@film_carousel = []
			while (@film_carousel.count < 3 && Film.count >= 3) do 
				id = rand(1..Film.count)
				@film_carousel << Film.find(id) unless @film_carousel.include? (Film.find(id))
			end
		end

    def film_params
      params.require(:film).permit(:title, :director, :year, :image, :description)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/actors/_form.html.erb
<%= form_for(@actor) do |f| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% @actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :born_year %><br>
    <%= f.datetime_field :born_year %>
  </div>
  <div class="field">
    <%= f.label :born_place %><br>
    <%= f.text_field :born_place %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_field :bio %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing actor</h1>

<%= render 'form' %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<table class="table">
  <tr>
    <th>Name</th>
    <th>Born Year</th>
    <th>Born Place</th>
    <th>Bio</th>
  </tr>

	<% @actors.each do |actor| %>
	<tr>
		<td><%= actor.name %></td>
		<td><%= actor.born_year.strftime("Born %d-%m-%Y (#{pluralize(actor.years_from_now, "Year")})") %></td>
		<td><%= actor.born_place %></td>
		<td><%= truncate(actor.bio) %></td>
	</tr>
	<% end %>

</table>

<%= link_to 'New Actor', new_actor_path %>

app/views/actors/new.html.erb
<h1>New actor</h1>

<%= render 'form' %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>

app/views/films/_form.html.erb
<%= form_for(@film) do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% @film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
		<%= label_tag("Actors") %>
		<%= autocomplete_field_tag 'actors', '', autocomplete_actor_name_actors_path, 'data-delimiter' => ', ', multiple: true, size: 75, id_element: '#some_element' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<%end %>

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render 'form' %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<h1>Listing films</h1>


<div id="myCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <div class="item active">
					<%= image_tag(@film_carousel[0].image) %>
            <div class="carousel-caption">
							<h1><%= @film_carousel[0].title %></h1>
							<p class="lead"><%= @film_carousel[0].description %></p>
              <a class="btn btn-large btn-primary" href="#">Sign up today</a>
            </div>
        </div>
        <div class="item">
					<%= image_tag(@film_carousel[1].image) %>
          <div class="container">
            <div class="carousel-caption">
							<h1><%= @film_carousel[1].title %></h1>
							<p class="lead"><%= @film_carousel[1].description %></p>
              <a class="btn btn-large btn-primary" href="#">Learn more</a>
            </div>
          </div>
        </div>
        <div class="item">
					<%= image_tag(@film_carousel[2].image) %>
          <div class="container">
            <div class="carousel-caption">
							<h1><%= @film_carousel[2].title %></h1>
							<p class="lead"><%= @film_carousel[2].description %></p>
              <a class="btn btn-large btn-primary" href="#">Learn more</a>
            </div>
          </div>
        </div>
      </div>

			<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
				<span class="control-left"><i class="fa fa-arrow-left fa-3x"></i></span>
			</a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
				<span class="control-right"><i class="fa fa-arrow-right fa-3x"></i></span>
			</a>
    </div>

<br>

app/views/films/list_films.html.erb
<table class="table">
  <tr>
    <th>Image</th>
    <th>Description</th>
    <th>Year</th>
    <th>Director</th>
    <th>Actors</th>
  </tr>

	<% @films.each do |film| %>
	<tr>
		<td><%= image_tag film.image, size: "100x150" %></td>
		<td><%= film.description %></td>
		<td><%= film.year %></td>
		<td><%= film.director %></td>
		<td><%= film.actors.map {|a| link_to(a.name, a) }.join(", ").html_safe %></td>
		<td><%= link_to 'Edit film', edit_film_path(film) %></td>
	</tr>
	<% end %>

</table>

<%= link_to 'New Film', new_film_path %>

app/views/films/new.html.erb
<h1>New film</h1>

<%= render 'form' %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @film.image %>
</p>
<p>
  <strong>Title:</strong>
  <%= @film.title %>
</p>

<p>
  <strong>Director:</strong>
  <%= @film.director %>
</p>

<p>
  <strong>Year:</strong>
  <%= @film.year %>
</p>

<%= link_to 'Edit', edit_film_path(@film) %> |
<%= link_to 'Back', films_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FilmbookV2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= nav_bar :brand => "FilmbookV2", :responsive => :true do %>
	<%= menu_group do %>
		<%= menu_item "Films", list_films_path %>
		<%= menu_item "Actors", list_actors_path %>
	<% end %>

	<%= menu_group :pull => :right do %>
		<% if user_signed_in? %>
			<%= menu_item "Profile", user_path(current_user) %>
			<%= menu_item "Logout", destroy_user_session_path, :method => :delete %>
		<% else %>
			<%= menu_item "Login", new_user_session_path %>
	  <% end %>
	<% end %>


<% end %>

<p class="notice"><%= notice %></p>
<div class="container">
	<%= yield %>
</div>

</body>
</html>